# Docs: https://aka.ms/yaml
name: $(Build.DefinitionName)-$(Date:yyyyMMdd))
trigger:
  - main

pool:
  vmImage: 'windows-latest'

variables:
  - group: MSPsUK KeyVault

stages:
  - stage: Release
    jobs:
      - job: Setup
        steps:
          - powershell: .\Bootstrap.ps1
            displayName: 'Install pre-requisites'
      - job: Build
        dependsOn: Setup
        steps:
          - task: PowerShell@2
            displayName: 'Build PowerShell Module'
            inputs:
              TargetType: filePath
              PWSH: true
              FilePath: '$(System.DefaultWorkingDirectory)\HaloAPI.build.ps1'
              Arguments: '-CopyModuleFiles -Configuration Production'
            
      - job: Release
        dependsOn: Build
        steps:
          - task: PowerShell@2
            displayName: 'Build PowerShell Module'
            inputs:
              TargetType: filePath
              PWSH: true
              FilePath: '$(System.DefaultWorkingDirectory)\HaloAPI.build.ps1'
              Arguments: '-PublishModule -Configuration Production'
            env:
              PSGalleryAPIKey: $(PSGalleryAPI)