# Docs: https://aka.ms/yaml
name: $(Build.DefinitionName)-$(Date:yyyyMMdd))
trigger:
  - main

pool:
  vmImage: 'windows-latest'

variables:
  - group: MSPsUK KeyVault

stages:
  - stage: Release
    jobs:
      - job: Setup
        steps:
          - powershell: .\Bootstrap.ps1
            displayName: 'Install pre-requisites'
      - job: Build
        dependsOn: Setup
        steps:
          - powershell: Invoke-Build -Configuration 'Production' -Task Clean, CopyModuleFiles
            displayName: 'Build PowerShell Module'
      - job: Release
        dependsOn: Build
        steps:
          - powershell: Invoke-Build -Configuration 'Production' -Task PublishModule
            displayName: 'Publish PowerShell Module'
            env:
              PSGalleryAPIKey: $(PSGalleryAPI)